### PR TITLE
Enables Fields and Include filters

### PR DESCRIPTION
**Pull request by darthwesker**

### CODE REVIEW

**Comment by kimkha** [comment]
Thank you for your PR, @darthwesker .

But I think your PR won't work with ra-data-simple-rest. Am I wrong?

**Comment by darthwesker** [comment]
Hi @kimkha,

You are correct. I tested the ra-data-simple-rest without applying the resource filters. Sorry.
My objective is to use the ra-data-simple-rest not only for the resources but also for other components which require the "include" filter. 

Do you think that is worth to make some changes here to accept the "include" and "fields" from the req.query.filter or to make a custom dataProvider?

**Comment by kimkha** [comment]
In that case, I think there is 2 ways to do:

1. Create new provider in react-admin, and put new 'include' property (as same level of 'filter', 'sort', 'range'). Then change this module to support 'include' (as same as 'sort', we can copy code and make it).
2. (I did it on my private project) On every model that needs 'include', I add a 'beforeRemote' hook, to add 'include' on server side, and don't change anything on client side.

The second one don't need to modify this module. But if you want the first, I'm very welcome your changes for it.

What do you think?

**Review by movibe — APPROVED** [review]

**Comment by darthwesker** [comment]
Hi @kimkha,

I created a new provider [react-admin-loopback](https://github.com/darthwesker/react-admin-loopback) and a new module based on this one [loopback-content-range](https://github.com/darthwesker/loopback-content-range). Developers that have no interest in use the 'include' property can continue to use this module.

**Comment by kimkha** [comment]
That's great, @darthwesker !

**Pull request closed without merging**
